config/routes.rb
IshankYammer::Application.routes.draw do

	as :user do
		match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
	end
	
	devise_for :users, :controllers => { :confirmations => "confirmations" }

  devise_for :admins

	resources :users 
	
	
	resource :posts

	resource :home, :controller => :home do
		post "follow"
		post "comment"
		get "new_user"
	end

	root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, :polymorphic => true
	validates :comment, :presence => true
end

app/models/following.rb
class Following < ActiveRecord::Base
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image
	validates :text, :presence => true
	validates :user_id, :presence => true
	belongs_to :user
	acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
	
	
	has_and_belongs_to_many :followers, :class_name => "User", :join_table => :followings , :foreign_key => :follower, :association_foreign_key => :master
	
	has_attached_file :image, :styles => { :thumb=> "100x100#", :small  => "400x400>" }
	has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin
  
  def attempt_set_password(params)
		p = {}
		p[:password] = params[:password]
		p[:password_confirmation] = params[:password_confirmation]
		update_attributes(p)
	end
	
	# new function to return whether a password has been set
	def has_no_password?
		self.encrypted_password.blank?
	end

	# new function to provide access to protected method unless_confirmed
	def only_if_unconfirmed
		unless_confirmed {yield}
	end
	
	def password_required?
		# Password is required if it is being set, but not for new records
		if !persisted? 
		  false
		else
		  !password.nil? || !password_confirmation.nil?
		end
	end
	
	
	
	
	
	
	
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #before_filter :authenticate_admin!
	before_filter :authenticate_user!
	
  #def check_authenticity
  #	try(:authenticate_admin!) || try(:authenticate_user!)
  #end
  
end

app/controllers/confirmations_controller.rb
# app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::PasswordsController
  # Remove the first skip_before_filter (:require_no_authentication) if you
  # don't want to enable logged users to access the confirmation page.
  skip_before_filter :require_no_authentication
  skip_before_filter :authenticate_user!

  # PUT /resource/confirmation
  def update
    with_unconfirmed_confirmable do
      if @confirmable.has_no_password?
        @confirmable.attempt_set_password(params[:user])
        if @confirmable.valid?
          do_confirm
        else
          do_show
          @confirmable.errors.clear #so that we wont render :new
        end
      else
        self.class.add_error_on(self, :email, :password_allready_set)
      end
    end

    if !@confirmable.errors.empty?
      render_with_scope :new
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    with_unconfirmed_confirmable do
      if @confirmable.has_no_password?
        do_show
      else
        do_confirm
      end
    end
    if !@confirmable.errors.empty?
      render_with_scope :new
    end
  end
  
  protected

  def with_unconfirmed_confirmable
    @confirmable = User.find_or_initialize_with_error_by(:confirmation_token, params[:confirmation_token])
    if !@confirmable.new_record?
      @confirmable.only_if_unconfirmed {yield}
    end
  end

  def do_show
    @confirmation_token = params[:confirmation_token]
    @requires_password = true
    self.resource = @confirmable
    render_with_scope :show
  end

  def do_confirm
    @confirmable.confirm!
    set_flash_message :notice, :confirmed
    sign_in_and_redirect(resource_name, @confirmable)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@post = Post.new
		
		not_to_display = current_user.id.to_s
		already_following = Following.where(:follower => current_user.id).collect {|f| f.master}.join(",")
		not_to_display += "," + already_following unless already_following.blank?
		
		@users = User.where("id not in (#{not_to_display})")
		@posts = Post.where("user_id in (#{not_to_display})").order "created_at desc" unless not_to_display.empty?
		
	end
	
	def new_user
	  	@user = User.new
	end
	
	def create_user
		
		@user = User.new(:email => params[:user][:email])
		if @user.save
			redirect_to :root, :alert => "Confirmation mail has been successfully send!"
		else
			render :action => "new"
		end	
	end
	
	def follow
		if(Following.where(:master => params[:master_id], :follower => current_user.id).empty?)
			Following.create(:master => params[:master_id], :follower => current_user.id)
		end	
	end
	
	def comment
		@comment = Comment.new(:comment => params[:comment], :user_id => current_user.id)
		post = Post.where(:id => params[:post_id]).first
		post.comments << @comment
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		@post = Post.new(params[:post])
		@post.user_id = current_user.id
		if(@post.save)
			redirect_to :root, :alert => "Post Successfully Created!"
		else
			redirect_to :root, :alert => "Error Saving post!"
		end				
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def new
  	@user = User.new
	end
	
	def create
		@user = User.new(:email => params[:email])
		if @user.save
			redirect_to :root, :alert => "Confirmation mail has been successfully send!"
		else
			render :action => "new"
		end	
	end
	
	def update
		@user = User.where(:id => params[:id]).first
		@user.name = params[:user][:name] unless params[:user][:name].blank?
		@user.image = params[:user][:image] unless params[:user][:image].blank?
		if @user.save
			redirect_to( :root, :alert => 'User was successfully updated.')
		else
			render :action => "edit"
		end
		
	end
	
	def edit
		@user = User.where(:id => params[:id]).first
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/comment.js.erb
$("#commentText<%= params[:post_id] %>").attr("value", "")
$("#latestComment<%= params[:post_id] %>").html("<%= escape_javascript(@comment.user.email + " -- " + @comment.comment) %>")

app/views/home/follow.js.erb
$("#followBox<%= params[:master_id] %>").remove();
$("#msg").html("You are now following him!");

app/views/home/index.html.erb
<script>
function follow(id) {
	$.ajax({
    url: '<%= follow_home_path %>', 
    dataType: 'script',
    type: 'post', 
    data: 'master_id='+id
	});
}

function addComment(id) {
	$.ajax({
    url: '<%= comment_home_path %>', 
    dataType: 'script',
    type: 'post', 
    data: 'post_id='+id+'&comment='+$("#commentText"+id).attr("value")
	});

}
</script>

<div id='msg'></div>

<%= link_to 'Add new user', new_user_path if admin_signed_in? %>

<h2>Welcome Home</h2>

<div class="mainBody">
	<% form_for @post, :html => { :multipart => true } do |f| %>
		<table width=100%>
			<tr>
				<td colspan=2>
					<%= f.text_area :text %>
				</td>
			</tr>	
			<tr>
				<td><%= f.file_field :image %></td>
				<td align='right'><%= f.submit %></td>
			</tr>
		</table>	
	<% end %>	
	<br><br><br>
	<% @posts.each do |post| %>
		<%= post.user.email %><br>
		<%= post.text %><br>
		<% post.comments.each do |comment| %>
			<span class='comments'><%= comment.user.email %> -- <%= comment.comment %></span>
		<% end %>
		<span class='comments' id='latestComment<%= post.id %>'></span>
		<textarea class='comment' id='commentText<%= post.id %>'></textarea><br>
		<span class='commentButton' id='comment<%= post.id %>' onclick = "addComment(<%= post.id %>)">Comment</span>
		<br><br>
	<% end %>
</div>



<div class='userContainer'>
	<% @users.each do |user| %>
	<span id='followBox<%= user.id =%>'>
		<%= user.email %>
		<input type='button' onclick="follow(<%= user.id =%>)" value="Follow" />
		<br><br>
	</span>	
	<% end %>
</div>

app/views/home/new_user.html.erb
<h2 align='center'>Add Admin</h2>

<%= form_for @user do |f| %>

  <table width="800" class="ShowTable" align='center'>
		<tr>
			<td>E - mail</td>
			<td><%= f.text_field :email %></td>
		</tr>	
		<tr>
			<td></td>
			<td><%= f.submit "Add User" %></td>
		</tr>	
  </table>
  
<% end %>
<script>
	$(".ShowTable tr:odd").addClass("AlternateRow");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IshankYammer</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if (user_signed_in?) %>
	<%= link_to 'Add User', new_user_path if current_user.is_admin == true %>
	<%= link_to 'Sign Out', destroy_admin_session_path, :method => :delete  %>
	<%= link_to 'Edit Profile', edit_user_path(current_user.id)  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %>
      prohibited this user from being saved:</h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% form_for @user, :html => { :multipart => true } do |f| %>
<table align='center'>
	<tr>	
		<td>Full Name</td>
		<td><%= f.text_field :name %></td>
	</tr>	
	<tr>	
		<td>Image:</td>
		<td><%= f.file_field :image %></td>
	</tr>
	<tr>	
		<td></td>
		<td><%= f.submit %></td>
	</tr>	
</table>
<% end %>

app/views/users/new.html.erb
<h2 align='center'>Add Admin</h2>

<%= form_tag users_path, :method => :post do %>


  
  <table width="800" class="ShowTable" align='center'>
		<tr>
			<td>E - mail</td>
			<td><%= email_field_tag :email %></td>
		</tr>	
		<tr>
			<td></td>
			<td><%= submit_tag "Add Admin" %></td>
		</tr>	
  </table>
  
<% end %>
<script>
	$(".ShowTable tr:odd").addClass("AlternateRow");
</script>